### PR TITLE
Update front-page ads config

### PR DESCRIPTION
**Pull request by imranolas**

### CODE REVIEW

**Comment by robin-marr-ft** [comment]
@imranolas 

Once slot on the page should have "out-of-page": true, this is an additional slot that is used to serve overlay ads, I'd recommend adding it to the leaderboard slot.

Cheers
rob

**Comment by imranolas** [comment]
@robin-marr-ft: Cheers, added that now. Otherwise good to go?

**Comment by robin-marr-ft** [comment]
:+1:  Go for it

**Pull request merged**
