### PR TITLE
No app styles

### PR DESCRIPTION
**Pull request by adgad**
/cc @Financial-Times/ads @andygnewman @i-like-robots @ironsidevsquincy 

Devolves responsibilty of declaring ad slots and defining styles to apps.

Apps can now just define ad slots in the usual o-ads way, within their HTML.

It might make some things more cumbersome e.g. lots of wholesale AB tests/multiple layouts.

o-ads is still (for now) initialised in next-ads-component.

Obviously needs to be a major release (will probably do a beta to play around with it more and migrate sites over)

e.g.
```
<div class="o-ads advertising__article-text o-ads__label-left" 
data-o-ads-name="mpu" 
data-o-ads-center="true" 
data-o-ads-label="true" 
data-o-ads-targeting="pos=mpu;" 
data-o-ads-formats-default="MediumRectangle,Responsive" 
data-o-ads-formats-small="MediumRectangle,Responsive" 
data-o-ads-formats-medium="MediumRectangle,Responsive" 
data-o-ads-formats-large="false" 
data-o-ads-formats-extra="false" 
aria-hidden="true">

</div>
```

### CODE REVIEW

**Comment by andygnewman** [comment]
That looks like an awful lot of stuff in that div that whoever is writing the app has to understand. Does it have to be so much or can we find a way of short handing it in the app (eg to mpu), which then gets expanded in the html on init through a configuration stored elsewhere. Then if we want to change any of the config for an 'mpu' it only needs to happen in one place. Though I guess this is what next-ads-component was doing and you're trying to get rid of?

**Comment by adgad** [comment]
I think it's a very valid point, and trying to find the balance. We were considering some common "formats" e.g. mpu, banner at a later point. Perhaps these could just be templates from next-ads-component (that you pass your own classnames to)?

My main goals are:
1) next-ads-component should have no knowledge of an app
2) I should be able to search within an app and understand what ads are there (a good example here would be the ad in the middle of the article body).
3) Less brittle :see_no_evil:

**Comment by adgad** [comment]
https://github.com/Financial-Times/next-ads-component/compare/refactor-redux?expand=1

This is probably a good half way house. Defines a set of slots (with no knowledge of where they exist) in next-ads-component. Reduces app code to something like this:

```
<div class="article-header-ad-placeholder ad-placeholder o-ads" data-o-ads-name="leaderboard" aria-hidden="true"></div>
```

Will be easier once we actually know what the proposition is!

**Comment by adgad** [comment]
Having tried the above, realised that there's because all the slots across the site have some differences, defining them as above doesn't really work and actually makes things more confusing. So, sticking with the initial approach of defining in the HTML.

This PR is now superceded by https://github.com/Financial-Times/next-ads-component/pull/146

**Pull request closed without merging**
