### PR TITLE
Give an example of how to use data-ads-layout with Ammit

### PR DESCRIPTION
**Pull request by commuterjoy**

### CODE REVIEW

**Comment by VladDubrovskis** [comment]
:+1:

**Comment by ironsidevsquincy** [comment]
How does this work? Currently we pass a layout value to the wrapper template directly from the app - https://github.com/Financial-Times/n-layout/blob/master/templates/wrapper.html#L8

**Comment by commuterjoy** [comment]
@ironsidevsquincy 

I guess just transpose the flags logic to whatever is generating the value of the attribute?

```
adsLayout: res.locals.flags.advertsAbTest ? 'variant': 'control'
...
```

from https://github.com/Financial-Times/next-front-page/blob/master/server/routes/front-page.js#L57

**Comment by ironsidevsquincy** [comment]
Shouldn't this go in `n-layout`'s readme, document the fact you can pass in a different ads layout?

**Comment by commuterjoy** [comment]
@ironsidevsquincy could do, but I just want to make sure anyone who reads 'ab testing x' knows that it's tied in with the flags system.

**Pull request merged**
